# .github/workflows/example.yml

name: Sync and merge upstream repository
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Inseo Yang'
          git config --global user.email 'y.1nseooo@gmail.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/EmoTrak/EmoTrak-FrontEnd.git
          git fetch upstream

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout dev
          git merge --no-edit upstream/dev
          git push origin dev

          git checkout main
          git merge --no-edit dev
          git push origin main

          # etc
