name: Sync and merge upstream repository
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 8 * * *" #Runs at 8:00 UTC(5:00 in Korea) every day.

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name '1nxeo'
          git config --global user.email 'y.1nseooo@gmail.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
           git remote add upstream https://github.com/EmoTrak/EmoTrak-FrontEnd.git
           git fetch upstream
           git checkout dev
           git merge -Xtheirs upstream/dev
           git checkout main
           git merge -Xtheirs dev
           git push origin main

          # etc
